2024-05-29 12:27:57,122 - cauldron - INFO - -- Cauldron Application --
2024-05-29 12:27:57,411 - cauldron - INFO - Initializing Cauldron Application
2024-05-29 12:28:01,530 - cauldron - INFO - SQL Agent Initialized
2024-05-29 12:28:07,772 - cauldron - INFO - UI Agent Initialized
2024-05-29 12:28:07,773 - cauldron - INFO - Initializing Interactive Demo Application
2024-05-29 12:28:07,774 - cauldron - INFO - Serial Port and ADC Constants Initialized
2024-05-29 12:28:09,507 - cauldron - INFO - Voice Interface Initialized
2024-05-29 12:28:09,508 - cauldron - INFO - Grid Layout Initialized
2024-05-29 12:28:09,518 - cauldron - INFO - Text Interaction Components Initialized
2024-05-29 12:28:09,520 - cauldron - INFO - Transcription Components Initialized
2024-05-29 12:28:09,524 - cauldron - ERROR - Error opening serial port: could not open port 'COM4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
Traceback (most recent call last):
  File "c:\Users\blake\Documents\GitHub\ebakery\cauldron-app\interactive_demo.py", line 83, in __init__
    self.ser = serial.Serial(self.SERIAL_PORT, self.BAUD_RATE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Python312\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Python312\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-05-29 12:28:09,534 - cauldron - WARNING - Serial connection could not be established.
2024-05-29 12:28:09,535 - cauldron - INFO - Cauldron Application Initialized
